### PR TITLE
Adding sign up and login use cases to main branch

### PR DESCRIPTION
**Pull request by goahead-lk-04**
I merged my code with the main branch, resolved all conflicts and it works just fine.
I haven't added a log-out use case as we don't have a user's profile view yet, where a button 'log out' must be

### CODE REVIEW

**Review by innaaa1 — APPROVED** [review]
It should work. Clean Architecture is implemented.

**Comment by matsevytyi** [comment]
Liza, you did a great work!!!

Everything is implemented well, in accordance to CA and SOLID, thank you very much.

Thanks to solving problems, related to the database, now I will be able to deal with all issues that appeared in my part and were invisible earlier.

Unfortunately, there is [one major issue, crucial for app functionality](https://github.com/matsevytyi/SharEvent/issues/13#issue-2011366317), that has to be solved.

Also, consider implementing [this feature](https://github.com/matsevytyi/SharEvent/issues/14#issue-2011367852) when you have time and desire. It doesn't require a lot of work, but will increase UX.

**Review by matsevytyi — APPROVED** [review]
Everything works well, looks okay in terms of SOLID and CA, hope issues will be solved later

**Review by Otakuhime167 — APPROVED** [review]
I have tested the code and the UI looks and works great. 
There are no dependency rule issues that I can see. CA also seems to be implemented well, and I can see some places where you used SOLID principles. Good job!

**Pull request merged**
