### PR TITLE
Added Filter and Search Use Cases

### PR DESCRIPTION
**Pull request by Otakuhime167**
Added working copy of filter and search use cases. Some notes:

- Filter cancel button doesn't unselect any buttons, because the buttons are JRadioButtons and cannot be unselected. Can consider switching to different type of buttons.

- Both Filter and Search presenters use the same method to show events as load events use case, can turn that to use Strategy design pattern to remove duplicated code

- Filter and Search working cases are a bit slow right now (~ 5 seconds to load) probably because they call DAO every time. Can change that to use already loaded list of events instead of using Database DAO.

### CODE REVIEW

**Review by matsevytyi — COMMENTED** [review]
everything works well, I liked it

solid, design patterns and CA are applied

**Review by matsevytyi — APPROVED** [review]
everything works well, I liked it

solid, design patterns and CA are applied

**Review by innaaa1 — APPROVED** [review]
CA is implemented nicely. The code looks clean and should work well. Thanks for changing the types in the add event.

**Review by goahead-lk-04 — APPROVED** [review]
Everything looks okay, should work just fine
Great!

**Pull request merged**
